const TEST_KEY = 'test';

const test = {
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    balance: 'Balance',
    bullet: 'Bullet',
    automaticFiring: 'Automatic firing',
    buyBullet: 'Purchase Bullets',
    casualMode: 'Casual Mode',
    tournamentMode: 'Tournament Mode',
    trialField: 'Demo game',
    realField: 'Real game',
    stayTuned: 'Stay Tuned',
    quickStart: 'Quick Start',
    NumBullet: 'Bullets',
    guest: 'Guest',
    volumeSetting: 'Volume Setting',
    music: 'Music',
    soundEffects: 'Sound',
    tips: 'Reminder',
    cancel: 'Cancel',
    confirm: 'Confirm',
    luckyDraw: 'Prize Draw',
    redemption: 'Exchange',
    buySuccess: 'Congratulations on acquiring!',
    luckyDrawTip2: 'Congrats! You’ve got ',
    Num: 'Remaining',
    shop: 'Shop',
    skin: 'Skin',
    lock: 'Lock',
    freeze: 'Freeze',
    bomb: 'Bomb',
    voucher: 'Voucher',
    use: 'Use',
    inUse: 'In Use',
    item: 'Item',
    youAreHere: 'You are here',
    purchase: 'Purchase',
    buyBulletCost: 'Must spend',
    leaveTip: 'Are you sure you want to leave the game?',
    reEnter: 'You are in the game now, do you want to re-enter?',
    kickedTip:
        'You have been kicked out of the game room, do you want to refresh the page and re-enter the game room?',
    buyBulletTip: 'Out of ammo, do you want to purchase more?',
    buySkillTip: 'You don’t have this skill, do you want to purchase it?',
    logoutTip: 'Login disconnected, do you want to refresh the current page?',
    posBombTip: 'Please select a location on the screen to place the bomb',
    aimFish: 'Please select the fish you want to attack',
    help: 'Help',
    times: 'times',
    help1:
        '1. Fish Points: Different fishes have different values, with the number of bullets obtained after capturing a fish being equal to the multiple of the cannon currently being used multiplied by the number of Fish Points. For example, if a fish with 50 Fish Points is captured using a 10x cannon, the number of bullets obtained is 50x10=500. Each different type of fish and their corresponding numbers of Fish Points are as follows:',
    help2:
        '2. Skill description: Players can apply the following skills in the game.',
    help2Super:
        'Super Skill: This is a passive skill which is automatically triggered after a certain number of fish have been captured by the player. It increases bullet power and doubles the firing speed.',
    help2Freeze:
        'Freezing Skill: Active skill which can be obtained either by killing certain types of fish or by directly purchasing. It can freeze most of the fish on the screen.',
    help2Lock:
        'Lock Skill: Active skill which can be obtained either by killing certain types of fish or by directly purchasing. It can automatically lock in place the fish on the screen which have the highest number of Fish Points; players can also select the fish which they want to lock in place.',
    help2Bomb:
        'Bomb Skill: Active skill which can be directly purchased. It will randomly kill groups of nearby fish on the screen.',
    help3: '3. Available cannon multiples: ',
    help31: '1,2,3,4,5,10,15,20',
    help4: '4. Other instructions',
    help41:
        'Redemption: Players can get some Fish Vouchers after capturing certain types of fish. Fish Vouchers can be redeemed in exchange for rewards.',
    help42:
        'Lucky draw: Players can qualify for 1 lucky draw after capturing 10 fish that each have at least 100 Fish Points. Rewards include bullets and currency.',
    help43:
        'Purchases: Players can purchase bullets inside the main hall, and can also purchase cannon skins or bullet effects by clicking on the cannon icon in the game.',
    tourSkip: 'Skip',
    tourStart: 'Start game',
    tour1: 'Click the drop-down button to select the currency',
    tour2: 'Game room will change <br/>according to which currency is selected',
    tour3:
        'In the demo game you can only experience the game, <br/>you must be in the real game in order to earn currency',
    tour4:
        'The system will automatically convert your digital currency into<br/> bullets when you enter a real game; any remaining <br/> bullets will be converted back into currency after you <br/> have left the room.',
    tour5: 'Control your cannon, click and catch <br/>fish to get more bullets',
    tour6: 'Use items to help you catch more <br/> and bigger fish',
    noData: 'No data',
    NetError: 'Problem with Internet connection, reconnecting',
    NetComeBack: 'Welcome back!',
    OtherLogin: 'Login error, please refresh and try again.',
    InputEmptyWarn: 'Input value cannot be blank!',
    Delete: 'Delete',
    buyItemTip: 'Confirm cost {cost_num} {cost_name},purchase {num} {name}.',
    buySkinTip: 'Confirm cost {num} {name},purchase {item}.',
    beyondBulletNum: 'Exceeds current ammunition limit',
    itemListTitle: 'Items stored',
    itemList1: 'Item types',
    itemList2: 'Sum of purchases',
    itemList3: 'Sum of prizes',
    search: 'Inquire',
    gameNo: 'Sessions',
    remainingNum: 'Amount remaining',
    gameListTitle: 'Game record',
    cost: 'Use up',
    prize: 'Winnings',
    delayUpdateAccount:
        'Updates to your balance might be delayed until blocks on the chain can be confirmed, please be patient.',
    enterGameCostTip:
        'The system converts {bringAmount} {currency} into {bulletNum} bullets. \n After you leave the room, any remaining bullets \n will then be converted back into your {currency}.',
    NoMoneyAmount:
        'The current currency surplus is insufficient, the minimum requirement to enter the market is {minAmount}{currency}, please go to top up or switch to other currencies.',
    platformDiffCurrencyEnterGameErr:
        'You have unfinished games, the system will automatically repeat.',
    arenaHelpRule11: '',
    arenaHelpRule12: '',
    arenaHelpRule13: '',
    arenaHelpRule21: '',
    arenaHelpRule22: '',
    arenaHelpRule23: '',
    arenaHelpRule24: '',
    arenaHelpRule31: '',
    arenaHelpRule32: '',
    arenaHelpRule33: '',
    arenaHelpRule34: '',
    arenaHelpRule35: '',
    arenaHelpRule41: '',
    arenaHelpRule42: '',
    arenaAwardTitle: '',
    arenaAwardItemTitle1: '',
    arenaAwardItemTitle2: '',
    arenaAwardItemTitle3: '',
    continueGame: '',
    noStart: '',
    sign: '',
    feeStr: '',
    allFirstPlace: '',
    firstPlace: '',
    secondPlace: '',
    thirdPlace: '',
    score: '',
    openTime: '',
    notInRank: '',
    arenaNotEndCurrency: '',
    arenaNotSupportCurrency: '',
    maintainQuitTip: '',
    maintainTip: '',
    keyboardEmpTip: '',
    arenaAwardDayRank: '',
    arenaAwardGradeRank: '',
    arenaTitle: '',
    matchTitle: '',
    maintaining: '',
    taskStartTip: '',
    taskCompletedTip: '',
    arenaTopPlayerTitle: '',
    arenaSettleTitle: '',
    arenaSettleReSign: '',
    arenaSettleReStatic: '',
    arenaSettleTpl: '',
    arenaSettle1: '',
    arenaSettle2: '',
    arenaRankScore: '',
    arenaRankAward: '',
    arenaRankTitle: '',
    arenaRankTab0: '',
    arenaRankTab1: '',
    arenaHelpTitle: '',
    arenaHelpTab0: '',
    arenaHelpTab1: '',
    arenaHelpTab2: '',
    arenaHelpTab3: '',
    arenaGiftTitle: '',
    arenaCompetitionTitle: '',
    arenaCompetitionSmallTip1: '',
    arenaCompetitionSmallTip2: '',
    arenaCompetitionSmallTip3: '',
    arenaCompetitionTip: '',
    arenaRewardTpl: '',
    [TEST_KEY]: 'test',
};
