/* eslint-disable */
/* tslint:disable */

export default {
    record_title_coin: '投币详情',
    record_title_reward: '赠送详情',
    record_title_deposit: '充币详情',
    record_title_withdraw: '提币详情',
    record_title_expenses: '消费详情',
    security: {
        changePassword: {
            title: '修改登录密码',
            set_title: '设置登录密码',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            ori_password: '原登录密码',
            new_password: '新登录密码',
            login_password: '登录密码',
            confirm_password: '确认密码',
            confirm_password_error: '新旧密码不一致!',
            tip_fail: '修改密码失败!',
            tip_success: '修改密码成功!',
        },
        changeEmail: {
            title: '修改邮箱',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            new_email: '新邮箱',
            success_tip: '修改邮箱成功!',
            fail_tip: '修改邮箱失败!',
        },
        changeAssetsPassword: {
            title: '资金密码',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            new_password: '请设置6位数字的资金密码',
            confirm_password: '确认密码',
            confirm_password_error: '密码输入不一致!',
            tip_error: '资金密码失败!',
            tip_success: '资金密码成功!',
            pay_password_required: '密码为6位数字',
        },
        emailCloseVerify: {
            title: '关闭邮箱验证',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            ori_password: '原登录密码',
            new_password: '新登录密码',
            confirm_password: '确认密码',
            tip_close_success: '关闭邮箱验证成功!',
            tip_close_fail: '关闭邮箱验证失败!',
            tip_open_success: '打开邮箱验证成功!',
            tip_open_fail: '打开邮箱验证失败!',
            con:
                '为了保障账户资金安全，至少需要开启1项双重身份验证方式。可在开启其他验证方式后再进行关闭。',
        },
        googleOpenVerify: {
            title: '绑定谷歌验证',
            con1:
                '谷歌验证器是一款动态口令工具，工作原理类似短信动态验证。绑定后每30s生成一个动态验证码，验证码可用于登录、提现、修改安全设置等操作的安全验证。',
            con2: '下载谷歌验证器APP',
            con3:
                'ios用户登录AppStore搜索“Authenticator”下载。安卓用户登录应用商店或使用手机浏览器搜索”谷歌验证器“下载。',
            con4: '在谷歌验证器中添加密钥并备份',
            con5:
                '打开谷歌验证器扫描下方二维码或手动输入下述密钥添加验证令牌。',
            con6:
                '*密钥用于手机更换或遗失找回谷歌验证器，绑定前请务必将上述密钥备份保存。',
            con7: '输入谷歌验证器中6位验证码',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            ori_password: '原登录密码',
            new_password: '新登录密码',
            confirm_password: '确认密码',
            form: {
                email_account: '邮箱账号',
                google_verify_code: '输入Google验证码',
                input_code: '请输入验证码',
                send_code: '发送验证码',
                bind_fail: '绑定失败',
                bind_success: '绑定成功',
                resend_code: '{seconds}s后重新发送',
            },
        },
        googleCloseVerify: {
            title: '关闭谷歌验证',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            ori_password: '原登录密码',
            new_password: '新登录密码',
            confirm_password: '确认密码',
            tip_close_success: '关闭谷歌验证成功!',
            tip_close_fail: '关闭谷歌验证失败!',
            tip_open_success: '打开谷歌验证成功!',
            tip_open_fail: '打开谷歌验证失败!',
            con:
                '为了保障账户资金安全，至少需要开启1项双重身份验证方式。可在开启其他验证方式后再进行关闭。',
        },
        googleChangeVerify: {
            title: '修改谷歌验证',
            title1: '在谷歌验证器中添加密钥并备份',
            con1:
                '打开谷歌验证器扫描下方二维码或手动输入下述密钥添加验证令牌。',
            con2:
                '*密钥用于手机更换或遗失找回谷歌验证器，绑定前请务必将上述密钥备份保存。',
            title2: '输入谷歌验证器中6位验证码',
            email_account: '邮箱账号',
            input_code: '请输入验证码',
            send_code: '发送验证码',
            resend_code: '{seconds}s后重新发送',
            ori_password: '原登录密码',
            new_password: '新登录密码',
            confirm_password: '确认密码',
            form: {
                email_account: '邮箱账号',
                google_verify_code: '新谷歌验证码',
                ori_verify_code: '原谷歌验证码',
                input_code: '请输入验证码',
                send_code: '发送验证码',
                resend_code: '{seconds}s后重新发送',
                tip_success: '修改谷歌验证成功!',
            },
        },
        intro: {
            titleSecurity: '安全设置',
            twoAuth: '二次验证',
            loginRecord: '登录记录',
            loginPass: '登录密码',
            emailSetting: '邮箱设置',
            assetsSecurity: '资金密码',
            emailAuth: '邮箱验证',
            googleAuth: '谷歌验证',
            passwordStrength: '安全强度',
            passwordStrengthRank_0: '低',
            passwordStrengthRank_1: '中',
            passwordStrengthRank_2: '高',
            forAccountSafe: '用于账户安全',
            forProtectAssets: '用于保护资产安全',
            forProtectMoney: '用于加强资金安全保护',
            forProtectGoogle: '用于登录、提币安全验证',
            loginTime: '登录时间',
            loginSource: '来源',
            ipAddress: 'IP地址',
        },
    },
    operate: '操作',
    collapse: '收起',
    recharge: '充币',
    withdraw: '提币',
    user_center: '用户中心',
    total_assets_converted: '总资产折合：',
    hide_small_assets: '隐藏小额资产',
    small_than: '小于',
    search_currency: '搜索货币',
    no_remind: '不再提示',
    no_remind_today: '今日不再提示',
    not_bind: '暂不绑定',
    totoal_asset: '总资产',
    available_asset: '可用资产',
    withdrawable_asset: '可提资产',
    unwithdrawable_asset: '不可提资产',
    freeze_asset: '冻结资产',
    bind_two_factor: '绑定双重身份验证',
    bind_two_factor_message:
        '用于提币时进行安全验证，为了保障账户资金安全，请至少再开启1项身份验证',
    bind_name_1: '谷歌验证器绑定',
    bind_name_2: '邮箱验证绑定',
    bind_intro_1: '提币安全验证，请绑定谷歌验证器',
    bind_intro_2: '默认二次验证方式',
    bind_to: '去绑定',
    bind_is: '已绑定',
    bind_non: '已关闭',
    finish_withdraw_0: '申请操作完成',
    finish_withdraw_1: '系统会尽快审核处理',
    recharge_record: '充币记录',
    withdraw_record: '提币记录',
    platform_give_record: '平台赠送',
    games_give_record: '游戏赠送',
    games_recharge_record: '游戏充币',
    order_no: '订单号',
    order_time: '时间',
    expenses_record: '消费记录',
    actName: '活动名称',
    expenses_amount: '消费金额',
    recharge_amount: '充币金额',
    gift_amount: '赠送金额',
    withdraw_amount: '提币金额',
    trans_hash: '交易哈希',
    service_charge: '手续费',
    pay_coin_currency: '投币类型',
    pay_coin_type: '投币项',
    pay_coin_amount: '投币金额',
    payback_amount: '返还金额',
    settle_status: '结算状态',
    valid_bet_amount: '有效投币金额',
    deselect_all: '取消全选',
    del_selected: '删除已选',
    set_read_all: '全部已读',
    message_tips: '我的消息（共{total}条消息，未读消息{unread}条）',
    message_detail: '消息详情',
    start_time: '开始时间',
    end_time: '结束时间',
    all_currency: '全部货币',
    select_currency: '货币选择',
    select_game: '游戏选择',
    all_game: '全部游戏',
    recently: '最近{recently}天',
    client_www: 'WEB',
    client_wap: '移动',
    client_android: '安卓客户端',
    client_ios: 'IOS客户端',
    arrival_amount: '到账数量',
    withdraw_alert:
        '不支持平台内部地址转账，请勿将资产提至任何非{currency}地址。',
    withdraw_addr: '提币地址',
    withdraw_tag: '提币标签',
    withdraw_minamount: '最小提币数量',
    withdraw_day_limit: '24小时提币限额 {dayMaxLimitAmount}',
    withdraw_single_limit: '单笔提币到账限额：{amount}',
    withdraw_day_max: '单日提币到账限额：{amount}（UTC+0 0:00重置）',
    rules_withdraw_addr_0: '请输入充币提币地址',
    rules_withdraw_addr_1: '{currency}地址无效',
    rules_withdraw_amount_0: '请输入提币数量',
    rules_withdraw_amount_1: '超过单笔提币审核额度',
    rules_withdraw_amount_2: '不足最小提币额度',
    rules_withdraw_amount_3: '钱包余额不足',
    rules_withdraw_amount_4: '超过单日最大提币额',
    rules_withdraw_amount_5: '无效金额',
    rules_withdraw_amount_6: '提币数量超出可用额度',
    rules_withdraw_amount_7: '超出单笔提币限额',
    rules_email_0: '请输入邮箱地址',
    rules_email: '请输入正确的邮箱地址',
    rules_optcode: '请输入正确验证码',
    tick_count: '{tickCount} 秒',
    send_code: '发送验证码',
    previous_page: '返回上一页',
    google_optcode: '谷歌验证码',
    rules_google_optcode: '请输入谷歌验证码',
    rules_optcode_6: '请输入6位数的验证码',
    rules_paypaw: '请输入资金密码',
    recharge_addr: '充币地址',
    address_tag: '地址标签',
    recharge_qrcode: '充币二维码',
    rules_recharge_alert:
        '禁止向如下地址充币任何非{currency}的资产，否则资产将不可找回。',
    forget_password: '忘记？',
    bet_record_count_m: '总计 <span>{total}</span> 笔投币记录',
    bet_record_valid_amount: '总有效投币额 <strong>{totalValidBet}</strong>',
    withdraw_status_1: '待审核',
    withdraw_status_2: '提币中',
    withdraw_status_3: '提币完成',
    withdraw_status_4: '审核驳回',
    withdraw_status_5: '提现失败',
    withdraw_status_6: '提币失败退回',
    order_status_1: '未结算',
    order_status_2: '已结算',
    match_status_1: '预测中',
    match_status_2: '处理中',
    match_status_3: '已结算',
    match_status_4: '已取消',
    match_status_5: '滚球回退',
    match_status_6: '滚球确认中',
    bet_match: '赛事投币',
    bet_games: '游戏投币',
    gameName: '游戏名',
    gain: '收获',
    bet_record: '投币记录',
    match_my_record: '我的投币',
    match_type_sport: '体育赛事',
    match_type_game: '电竞赛事',
    recharge_chain_times:
        '您充币至上述地址后，需要整个网络节点的确认，{times} 次网络确认后到账。',
    recharge_min_amount: '最小充值数 {amount}',
    recharge_refresh: '充币到账后需要刷新游戏',
    importance: '必看',
    memo_desc: '填写错误可能导致资产损失，请仔细核对。',
    rules_withdraw_addr_chain: '请检查您的提币地址是否与所选币种相同',
    bet_record_count: '总计{total}笔投币记录，总有效投币额：{totalValidBet}',
    expired_record: '奖励过期记录',
    expired_amount: '过期奖励',
    expired_time: '过期时间',
    acct_expired_tips: '本月剩余 {amount} 即将到期。',
    acct_expired_toast: '活动奖励即将过期',
    register_award_tip:
        '恭喜您获得 {num} {currency} 的奖励，请至个人中心-交易记录中查看',
    input_asset_password: '请输入6位数字的资金密码',
    track_award_title: '专属福利',
    track_award_tip: 'Bitgame 送您定制奖励<span>{amount}{currency}</span>',
    track_award_get: '立即领取',
};
