[package]
name = "tokio-zookeeper"
version = "0.1.0"
authors = ["zsytssk <zsytssk@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.27"
tokio = "0.1.21"
failure = "0.1.5"
byteorder = "1.3.1"